import { Company, CompanyId, MarketEvent } from "./types";

export const INITIAL_CASH = 10000;
export const INITIAL_STOCK_PRICE = 2000;
export const INITIAL_STOCK_QUANTITY = 15;
export const MAX_HOLDING_PER_COMPANY = 7;
export const ROUND_GAME_MINUTES = 60;
export const TICK_MINUTES = 5;
export const MARKET_EVENTS_PER_ROUND = 24;
export const DEFAULT_PLAYER_COUNT = 8;
export const DEFAULT_ROUND_REAL_SECONDS = 600;

export const COMPANIES: Company[] = [
  {
    id: "disconnectedTelecom",
    name: "단절통신",
    shortName: "단절",
    color: "#2563EB",
  },
  {
    id: "deathLife",
    name: "사망생명",
    shortName: "사망",
    color: "#DC2626",
  },
  {
    id: "stoneAgeElectronics",
    name: "석기전자",
    shortName: "석기",
    color: "#7C3AED",
  },
  {
    id: "earthquakeConstruction",
    name: "지진건설",
    shortName: "지진",
    color: "#D97706",
  },
  {
    id: "bankruptBank",
    name: "파산은행",
    shortName: "파산",
    color: "#059669",
  },
];

export const COMPANY_IDS = COMPANIES.map((company) => company.id);

export const createEmptyHoldings = (): Record<CompanyId, number> => ({
  disconnectedTelecom: 0,
  deathLife: 0,
  stoneAgeElectronics: 0,
  earthquakeConstruction: 0,
  bankruptBank: 0,
});

export const ROUND_ONE_EVENTS: MarketEvent[] = [
  {
    id: "r1-005-disconnectedTelecom",
    round: 1,
    minute: 5,
    companyId: "disconnectedTelecom",
    change: 400,
    priceAfter: 2400,
    pair: { firstPlayerNumber: 3, secondPlayerNumber: 4 },
  },
  {
    id: "r1-005-stoneAgeElectronics",
    round: 1,
    minute: 5,
    companyId: "stoneAgeElectronics",
    change: 600,
    priceAfter: 2600,
    pair: { firstPlayerNumber: 2, secondPlayerNumber: 3 },
  },
  {
    id: "r1-010-earthquakeConstruction",
    round: 1,
    minute: 10,
    companyId: "earthquakeConstruction",
    change: 400,
    priceAfter: 2400,
    pair: { firstPlayerNumber: 4, secondPlayerNumber: 5 },
  },
  {
    id: "r1-010-bankruptBank",
    round: 1,
    minute: 10,
    companyId: "bankruptBank",
    change: -500,
    priceAfter: 1500,
    pair: { firstPlayerNumber: 1, secondPlayerNumber: 2 },
  },
  {
    id: "r1-015-deathLife",
    round: 1,
    minute: 15,
    companyId: "deathLife",
    change: -500,
    priceAfter: 1500,
    pair: { firstPlayerNumber: 7, secondPlayerNumber: 8 },
  },
  {
    id: "r1-015-earthquakeConstruction",
    round: 1,
    minute: 15,
    companyId: "earthquakeConstruction",
    change: -500,
    priceAfter: 1900,
    pair: { firstPlayerNumber: 3, secondPlayerNumber: 4 },
  },
  {
    id: "r1-020-disconnectedTelecom",
    round: 1,
    minute: 20,
    companyId: "disconnectedTelecom",
    change: 500,
    priceAfter: 2900,
    pair: { firstPlayerNumber: 6, secondPlayerNumber: 7 },
  },
  {
    id: "r1-020-deathLife",
    round: 1,
    minute: 20,
    companyId: "deathLife",
    change: 600,
    priceAfter: 2100,
    pair: { firstPlayerNumber: 8, secondPlayerNumber: 1 },
  },
  {
    id: "r1-025-stoneAgeElectronics",
    round: 1,
    minute: 25,
    companyId: "stoneAgeElectronics",
    change: -600,
    priceAfter: 2000,
    pair: { firstPlayerNumber: 5, secondPlayerNumber: 6 },
  },
  {
    id: "r1-025-bankruptBank",
    round: 1,
    minute: 25,
    companyId: "bankruptBank",
    change: 700,
    priceAfter: 2200,
    pair: { firstPlayerNumber: 3, secondPlayerNumber: 4 },
  },
  {
    id: "r1-030-earthquakeConstruction",
    round: 1,
    minute: 30,
    companyId: "earthquakeConstruction",
    change: 700,
    priceAfter: 2600,
    pair: { firstPlayerNumber: 5, secondPlayerNumber: 6 },
  },
  {
    id: "r1-030-bankruptBank",
    round: 1,
    minute: 30,
    companyId: "bankruptBank",
    change: 400,
    priceAfter: 2600,
    pair: { firstPlayerNumber: 6, secondPlayerNumber: 7 },
  },
  {
    id: "r1-035-disconnectedTelecom",
    round: 1,
    minute: 35,
    companyId: "disconnectedTelecom",
    change: -900,
    priceAfter: 2000,
    pair: { firstPlayerNumber: 4, secondPlayerNumber: 5 },
  },
  {
    id: "r1-035-earthquakeConstruction",
    round: 1,
    minute: 35,
    companyId: "earthquakeConstruction",
    change: -400,
    priceAfter: 2200,
    pair: { firstPlayerNumber: 2, secondPlayerNumber: 3 },
  },
  {
    id: "r1-040-stoneAgeElectronics",
    round: 1,
    minute: 40,
    companyId: "stoneAgeElectronics",
    change: -400,
    priceAfter: 1600,
    pair: { firstPlayerNumber: 7, secondPlayerNumber: 8 },
  },
  {
    id: "r1-040-bankruptBank",
    round: 1,
    minute: 40,
    companyId: "bankruptBank",
    change: -900,
    priceAfter: 1700,
    pair: { firstPlayerNumber: 8, secondPlayerNumber: 1 },
  },
  {
    id: "r1-045-disconnectedTelecom",
    round: 1,
    minute: 45,
    companyId: "disconnectedTelecom",
    change: 600,
    priceAfter: 2600,
    pair: { firstPlayerNumber: 1, secondPlayerNumber: 2 },
  },
  {
    id: "r1-045-earthquakeConstruction",
    round: 1,
    minute: 45,
    companyId: "earthquakeConstruction",
    change: -800,
    priceAfter: 1400,
    pair: { firstPlayerNumber: 6, secondPlayerNumber: 7 },
  },
  {
    id: "r1-050-deathLife",
    round: 1,
    minute: 50,
    companyId: "deathLife",
    change: 500,
    priceAfter: 2600,
    pair: { firstPlayerNumber: 1, secondPlayerNumber: 2 },
  },
  {
    id: "r1-050-bankruptBank",
    round: 1,
    minute: 50,
    companyId: "bankruptBank",
    change: -400,
    priceAfter: 1300,
    pair: { firstPlayerNumber: 5, secondPlayerNumber: 6 },
  },
  {
    id: "r1-055-disconnectedTelecom",
    round: 1,
    minute: 55,
    companyId: "disconnectedTelecom",
    change: 400,
    priceAfter: 3000,
    pair: { firstPlayerNumber: 8, secondPlayerNumber: 1 },
  },
  {
    id: "r1-055-earthquakeConstruction",
    round: 1,
    minute: 55,
    companyId: "earthquakeConstruction",
    change: 800,
    priceAfter: 2200,
    pair: { firstPlayerNumber: 7, secondPlayerNumber: 8 },
  },
  {
    id: "r1-060-disconnectedTelecom",
    round: 1,
    minute: 60,
    companyId: "disconnectedTelecom",
    change: -700,
    priceAfter: 2300,
    pair: { firstPlayerNumber: 2, secondPlayerNumber: 3 },
  },
  {
    id: "r1-060-deathLife",
    round: 1,
    minute: 60,
    companyId: "deathLife",
    change: 400,
    priceAfter: 3000,
    pair: { firstPlayerNumber: 4, secondPlayerNumber: 5 },
  },
];
